### ISSUE TITLE
Modify derivation path for the HD wallet to use Aion's own coin type

### ISSUE THREAD

**Issue by centrys-otniel** [aionnetwork/aion_ui#115]
Currently the Wallet uses the derivation path for ether - `44'/60'/...` but should use Aion's own derivation path.

The proposed path is `44'/425'`, but we should monitor the registered coin types on [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) and update the path after Aion was added to this list

**Comment by qoire** [comment]
Let's push to add this change in first, satoshilabs are going to be looking for software using this path anyhow, it makes sense for us to use it without them confirming.

**Comment by centrys-cristian-ilca** [comment]
Fixed with this PR 
https://github.com/aionnetwork/aion_ui/pull/120
