### ISSUE TITLE
Address mismatch between Wallet and standard bip44

### ISSUE THREAD

**Issue by gurdeepakjoshi** [aionnetwork/aion_ui#116]
Trying to understand , why there is an address mismatch from same bip44 path and seed value

Seed value : empower april ill spoon grab fringe vehicle river dragon have forget today
Bip44 path : 44'/60'/0'/0'/0'

Address from wallet : a067366984712e24e6758684c2ef8a978785ac403e7ba2ace04ce1f1024a07e9

Following are public key and address generated from standard bip44 python script.
Public key : e77ba23bc030cbca2fa5c3cee25ea4ae851e947a1d4d0e54fe9ccced9f339b19
Address : a0d4f56e8baaa2372fbfa9051fc4419f0874ddc8ff20cecf600aa0701cc3351c

FYI, this script has been tested on Ledger Nano S to validate public keys from seed and bip44 path. 
```
from nose.tools import *
from crypto_helper import *

import nacl
from nacl.signing import SigningKey

import hashlib
import os

phrase = "empower april ill spoon grab fringe vehicle river dragon have forget today"

# verifies public key from ledger with expected public key from mnemonic bip39
def test_get_public_key():

    # generate an identical transaction
    seed = mnemonic_to_bip39seed(phrase, passphrase="")

    pk, cc = bip39_to_slip0010_master(seed)
    pk, cc = derive_child(pk, cc, 44)
    pk, cc = derive_child(pk, cc, 60)
    pk, cc = derive_child(pk, cc, 0)
    pk, cc = derive_child(pk, cc, 0)
    pk, cc = derive_child(pk, cc, 0)

    seed_pub_key, sec_key = nacl.bindings.crypto_sign_seed_keypair(pk)

    print "\nExpected public key : "+seed_pub_key.encode('hex')+"\n"
```

Module used to map address from public key
```
Wallet.prototype.pubToAddress= function (){
    var Pub = Buffer.from(this.pubKey,'hex');
    var buf = new Buffer (['0xA0']);
    var buff = Buffer.concat([buf,new Buffer(blake2B(Pub,'',32).slice(1,32))]);
    console.log(new Buffer (blake2B(Pub,'',32)).toString('hex'));
    return buff.toString('hex');
}
```
Test script package : [test.tar.gz](https://github.com/aionnetwork/aion_ui/files/2121282/test.tar.gz)

Second testcase : when passphrase is "1"
Seed : other battle kid express news recycle ride spread violin work exotic thumb
bip44 : 44'/60'/0'/0'/0'

Address from wallet : a0bacb5c6ca74bd8785816d06454814ee1a22262fa734c88e8ac5e8c264ddd76

Public key and address from script
Public key : 870a334e860172a79d4d604da51978950ca5611c4cfdf99493c9b2c6535a43ad
Address : a069957da939a5c7041454be00db36d80ad0e003a3e040fb0a2b376af872c3c0

**Comment by centrys-otniel** [comment]
S the first part of the issue was that  the Mnemonic was not properly converted to a seed and that caused all the derivations on a wrong path. This was solved as part of https://github.com/aionnetwork/aion_ui/pull/117. There's a test case that verifies that the secret key is just the same as the one in the py test case, but the public key is different than expected

**Comment by centrys-otniel** [comment]
FIxed and merged. @gurdeepakjoshi if you could please confirm, I'll close the issue

**Comment by gurdeepakjoshi** [comment]
Confirmed. The address matches with standard bip44 for following test case. Closing the issue.

Seed : loyal tornado camp wise top myth base reunion receive drink tornado moon
Path : 44'/60'/0/0/0

From script
Public key : 66f74df4d1a44b6fd5455aeac840db115acc1269f7cd294e97ff29fa314e992f
Address : 0xa075d3f1147d635dd48efa9f109dd8714215c64021fc84bddc7f0d0cc6c16170

From wallet
Address : 0xa075d3f1147d635dd48efa9f109dd8714215c64021fc84bddc7f0d0cc6c16170
