### ISSUE TITLE
Modifications for Version 1.0.0

### ISSUE THREAD

**Issue by gurdeepakjoshi** [aionnetwork/aion_ui#119]
Hi Team, 

Here are the required modifications for v1.0.0

1) Modify version number to 1.0.0	

2) Modify hd derivation path to 44/425/0/0/counter			

3) Modify icon for lock / unlock to following icons(icon-connected-50.png and icon-disconnected-50.png)
![002-lock-padlock](https://user-images.githubusercontent.com/31374898/42282805-b309ca3a-7f75-11e8-9ba8-80d66de2b6f2.png)
![003-unlock-padlock](https://user-images.githubusercontent.com/31374898/42282806-b31c160e-7f75-11e8-8b5d-8e3ec513e7f5.png)

4) Remove 'tcp' protocol textbox from Setting screen

5) Add a option to "Export keystory" in Accounts screen for all accounts. The icon should be placed after unlock icon attached following. Once user clicks on this icon, a pop up will open asking the user where to save the keystore file. The user shouldn't be allowed to change name of keystore file while saving.
![export](https://user-images.githubusercontent.com/31374898/42247993-65142a70-7ef1-11e8-80ab-42fee7ae7cb9.png)

6) Add default prefix in imported account names ("Imported"). Also, remove import icon from account address

7) Package the build as Ubuntu executable (including the required jdk) preferably deb. So that the user can just launch wallet and start interacting (without the need to install jdk)

8) Button colour code should be
	- Colour code for primary button : #4221cc
	- Colour code of cancel/close button : #eae9fb

**Comment by centrys-otniel** [comment]
Fixed by:
* #120 
* #121 

With the following notes:
* isssue no.1 - Nothing to fix, version is read from git tag, not static
* issue no.7 - Will be handled by @gurdeepakjoshi
