### ISSUE TITLE
Properly setting a working directory

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#46]
Currently a little confusing to have a ``.aion`` folder on the users home folder but default to ``$(PWD)`` for the ``keystore`` folder, we should consider placing everything frontend related into ``.aion``

**Comment by qoire** [comment]
Hey, could you resubmit this (with explanations) as an issue on aionnetwork/aion repository?

**Comment by qoire** [comment]
I believe this task was just added to the kernel, can we consider this issue resolved?

**Comment by centrys-otniel** [comment]
Yes, I was just looking for the corresponding PRs

**Comment by centrys-otniel** [comment]
Resolved in: 
* https://github.com/aionnetwork/aion_ui/pull/80
* https://github.com/aionnetwork/aion_ui/pull/102
