### ISSUE TITLE
[Minor] Unhandled return case

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#56]
``Keystore.create()`` has the potential of returning an empty string:

https://github.com/aionnetwork/aion_ui/blob/f0a8416ec79b53dac1bfe4de2b11e281d6c77997/src/main/java/org/aion/wallet/account/AccountManager.java#L88-L91

Such a case should be handled

**Comment by qoire** [comment]
A similar case:

https://github.com/aionnetwork/aion_ui/blob/f0a8416ec79b53dac1bfe4de2b11e281d6c77997/src/main/java/org/aion/wallet/account/AccountManager.java#L145

**Comment by centrys-otniel** [comment]
solved in https://github.com/aionnetwork/aion_ui/pull/76
