### ISSUE TITLE
[Enhancement] Introduction of jsr305

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#57]
Suggest we introduce JSR305 (threading and null annotations) to the codebase. This will improve code maintainability and serve as a good self-documenting practice. Also integrates with existing static analyzers such as FindBugs.

https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305

**Comment by centrys-otniel** [comment]
JSR305 jar added in https://github.com/aionnetwork/aion_ui/pull/101
This will be used as development continues
