### ISSUE TITLE
[Minor] Prefer ScheduledExecutorService to Timer

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#58]
As noted by:
https://stackoverflow.com/questions/409932/java-timer-vs-executorservice

``ScheduledExecutorService`` gives us increase flexibility in error handling, as well as automatic respawn in an exceptional situation.

https://github.com/aionnetwork/aion_ui/blob/f0a8416ec79b53dac1bfe4de2b11e281d6c77997/src/main/java/org/aion/wallet/account/AccountManager.java#L57

Unless I am missing some contextual information

**Comment by centrys-otniel** [comment]
Resolved in https://github.com/aionnetwork/aion_ui/pull/75
