### ISSUE TITLE
[Discussion] Swap implementation to sendRawTransaction

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#62]
(This is related to #61)
This will require more discussion from us, but here is the rationale for swapping the implementation to ``sendRawTransaction`` rather than ``sendSignedTransaction``:

## Rationale

``sendSignedTransaction`` exposes the users password and private key (potentially both) to the node processing the data. We should instead use ``sendRawTransaction``, which only exposes the signature (hence the address) of the user and the contents of the transaction.

https://github.com/aionnetwork/aion_ui/blob/a8ff53cc5af4a9bcbf8d7a080b018d93e85e5652/src/main/java/org/aion/wallet/connector/api/ApiBlockchainConnector.java#L250-L253

**Comment by qoire** [comment]
Disregard this, JavaAPI most likely does client side signing, so API is safe to use

**Comment by centrys-otniel** [comment]
Yes, the API does sign on the client side
