### ISSUE TITLE
[Enhancement] JSONRPC Fallback

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#63]
## TLDR

Add in a fallback to web3 if JavaAPI is unsupported on the node.

## Rationale

Traditionally, we've viewed our JSON-RPC stack (web3.js) as our mainstream API offering and Java API for more performant backends (such as our dashboard). As such, it may be that most publically hosted nodes only choose to offer JSON-RPC as the standard, this is due to a myriad of reasons such as performance, availability and ability to handle throughput. It makes sense for the frontend to fallback or default to such an option when JavaAPI is not available.

**Comment by centrys-otniel** [comment]
@qoire, Is this still asomething that you'll want to implement at a later time, or should we just scrap the idea?

**Comment by qoire** [comment]
Closing, freezing this feature request until after handoff
