### ISSUE TITLE
[Major] Transaction Sorting Comparator

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#64]
Currently, the transaction sorting comparator uses transaction ``timestamp`` fields for comparison. To my knowledge there is no check that asserts chronological ordering on that field within the Aion kernel.

This means that it is possible for a user to craft two transactions in an incorrect chronological ordering, but correct nonce ordering, effectively one transaction would appear earlier than the other, even if it was processed later.

The standard for ordering transaction should always be the transaction ``nonce`` field.

https://github.com/aionnetwork/aion_ui/blob/4a62dba7852af777a181ad4be74a20d1c86e6154/src/main/java/org/aion/wallet/connector/api/ApiBlockchainConnector.java#L498-L505

**Comment by centrys-sergiu** [comment]
I don't think it should be sorted by nonce, but by block height. Nonce is generated by pool, there are multiple pools starting with nonce 0 and increasing nonce for each transaction. If I mine on two pools, the transactions get mixed in wrong order.

**Comment by qoire** [comment]
@centrys-sergiu Not sure I follow, ``nonce`` is generated by the user sending the transaction. If you go through a node this is usually done by the pool but that is not always the case. When we emit a client side signed transaction the ``nonce`` is actually generated by the client (in this case the wallet) itself.

``nonce``s are always going to be in a unique monotonically increasing order, so sorting based on nonce order is guarantees ordering, whereas sorting by block numbers does not give you ordering given that two transactions from the same account appear in the same block.

**Comment by qoire** [comment]
@centrys-otniel LGTM, you could sort both by position index if parsing by block.

**Comment by centrys-otniel** [comment]
Final fix in https://github.com/aionnetwork/aion_ui/pull/103
