### ISSUE TITLE
[Minor] Deal with possible block "fault" from API

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#65]
This will be related to the larger topic of chain reorganization, but can be encapsulated as a simpler algorithm for now:

Currently, blocks are requested from the client under the assumption that the return will be a continuous chain of blocks. I've confirmed with @AionJayT that this assumption does not hold, it is unlikely but possible for the API to return a chain of blocks that are from two separate blockchains. This occurs when the blockchain re-organizes as the API is preparing the blocks for response on the server (Aion kernel) side.

### Resolution

The resolution will come in the form of adding logic to deal with chain re-orgs, but until that is complete a simple sanitation check of the outputs, along with a re-request will be sufficient.

**Comment by centrys-otniel** [comment]
Resoved in https://github.com/aionnetwork/aion_ui/pull/75
