### ISSUE TITLE
[Enhancement] Transaction Resubmission Mechanism

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#66]
### Problem

Energy prices can be fickle, especially when the network becomes congested, transactions can be backlogged and possibly unprocessed for days if energy prices are not set correctly. 

### Resolution

The client should offer some mechanism to allow a user to "resubmit" a transaction, that is send a transaction with the same ``nonce``, but with a changed energy price. Coordinate with @AionJayT to find out what the transaction replacement policy is currently in our transaction pools.

**Comment by centrys-otniel** [comment]
Resolved in https://github.com/aionnetwork/aion_ui/pull/88
