### ISSUE TITLE
[Enhancement] Implement blockchain re-org detection & resolution

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_ui#67]
This relates mainly to the historical view of the transaction (``HistoryController.java``), most of this is based on my initial reading of the code, please correct any mistakes I make.

## Problem

The HistoryController (from my reading) derives its state primarily from the BlockchainConnector, the connector currently keeps multiple in-memory data structures to populate the state. There is the view:

~~~~java
private final Map<String, SortedSet<TransactionDTO>> addressToTransactions = Collections.synchronizedMap(new HashMap<>());
~~~~

Inside ``AccountManager.java`` that keeps track of transactions that have been assigned to an account, I believe the following scenarios are possible, due to us "concatenating" the state of accounts:

### Scenario 1: User transactions end up on two separate forks

This is an unlikely scenario that may occur when a user submits a transaction, then resubmits the same transaction as the blockchain is re-organizing:

~~~~
TX[S, A, N] = Transaction with state change S from account A at nonce N

                                      Chain A_1 TX[S_1, A, 1]
                                       |
Chain A [S, A, 0] -------> |
                                       |
                                      Chain A_2 TX[S_2, A, 1]  -------> Chain A_2 TX[S_2, A, 2]
~~~~ 

Let's assume that the local node retrieves blocks in the following order:

~~~~
Chain A -> Chain A_1 --> Re-org! --> Chain A_2 --> Chain_A_2
~~~~

Assume that during those moments in time we happen to query the blockchain (per block) to retrieve the latest account state. Then it is possible for us to store both ``TX[S_1, A, 1]`` and ``TX[S_2, A, 1]`` as transactions, this is inconsistent state.

### Scenario 2: User transaction ends up on side-chain

This scenario is similar to scenario 1, with the exception that the user transaction did _not_ actually make it onto the blockchain. Instead it ended up on a sidechain (for the time being). In this scenario, we would record a transaction as being submitted, and processed by the blockchain. But after a certain amount of time the blockchain re-organizes to a chain _without_ the transaction.

### Resolution

An easy resolution is to trail the "tip" of the blockchain, usually short reorganizations occur only within a few blocks of the network head (1-3 blocks). By trailing, we can _usually_ ignore reorganization. But this is not a good solution in that long re-organizations sometimes do happen.

The best solution is to detect re-organization logic to a certain depth (192 blocks within the blockchain itself), and assume a _pending_ state.

#### Re-org Detection & Resolution

Pretty simple, the wallet must keep track of a certain pending state (for example the 192 last blocks requested). There are a few cases the wallet must deal with:

1) The next blocks you request from the blockchain is not continuous with the blockchain stored inside the client memory. This means the blockchain has re-organized and is now on a different chain, here we want to find the common ancestor by comparing the locally stored block hashes to the remote, once we find the ancestor we should "pop" our temporary state back to that block and rebuild from there.

2) The blockchain now has a tip that is smaller than you. This is possible as block number does not dictate total difficulty. The resolution is similar, you must pop the same up until the common ancestor and rebuild from there.

If the re-organization is not successful (this means that re-organization goes beyond our stored memory of 192 blocks), then the program should enter a fail state, and ask the user to reboot (additionally it should warn the users of what just occured).

**Comment by centrys-otniel** [comment]
Resolved in 
https://github.com/aionnetwork/aion_ui/pull/90
https://github.com/aionnetwork/aion_ui/pull/96

**Comment by centrys-otniel** [comment]
Resolved in
#90
#96
