### ISSUE TITLE
API not initialized yet!

### ISSUE THREAD

**Issue by wezchow** [aionnetwork/aion_ui#68]
Hi guys, 

Just a quick question when i use the wallet, the console keep showing
`API not initialized yet!`

Seems it requires some configuration to it? or to the node?
My node info:
`Aion(J)/v0.2.7.1bbeec1/linux/Java-10.0.1`

And using the dev branch of aion_ui

Thanks,
Wesley

**Comment by centrys-cristian-ilca** [comment]
Hello,
You will get this error message in case that there is no connection to a node for your wallet. 
One easy way to fix this is to get an address from a working node and input it's address and port in the settings tab of the wallet; after clicking on Apply, the settings should take effect immediately and the wallet will connect to the specified node.

Best regards,
Cristian.

**Comment by wezchow** [comment]
Hi,

In fact, I did setup all the connection strings as following snapshot, but still no luck ... the console keep popping up the error msgs ...

That is my personal node address and the JAVA API port has opened for public access. I am using MacOS for testing ... 

![image](https://user-images.githubusercontent.com/4617522/40795887-f5249fa8-6535-11e8-9bc4-5a69e913dfae.png)

**Comment by wezchow** [comment]
Following is my config, I have tried to replace the IP address of `<java active="true" ip="127.0.0.1" port="8547"></java>` with public address but still not works ... 

`<api>
                <rpc active="true" ip="127.0.0.1" port="8545">
                        
                        <cors-enabled>true</cors-enabled>
                        
                        <apis-enabled>web3,eth,personal,stratum,net</apis-enabled>
                        
                        <threads>2</threads>
                </rpc>
                <java active="true" ip="127.0.0.1" port="8547"></java>
                <nrg-recommendation>
                        
                        <default>10E9</default>
                        
                        <max>100E9</max>
                        
                        <oracle-enabled>false</oracle-enabled>
                </nrg-recommendation>
        </api>`

**Comment by centrys-sergiu** [comment]
Since you are running aion node on the same machine as the UI app, you should use internal ip address not your external one. Easy fix should be using 127.0.0.1 instead of 118.25.225.163, and don't replace it either in the node. The values in config file should be either 127.0.0.1 (for internal usage) or 0.0.0.0 (for external usage - so you can connect remotely)

**Comment by wezchow** [comment]
Thanks @centrys-sergiu , my intention is to use the wallet remotely. Now I am pretty sure it's a kernel issue, even I config the address with 0.0.0.0, still fails to make the connection. Hence I am closing this issue here. Good work anyway folks ...

**Comment by centrys-sergiu** [comment]
Check the config of the kernel as well. Good luck :)
